version: '3.8'

# services

# 1. backend
services: 
  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports: 
      - "4003:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/api-db
    volumes:
      - ./api:/app
    networks:
      - api-network


# 2. mongo
  db-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - api-network
    volumes:
      - db-mongo:/data/db
    

# 3. mongo-express
  express-mongo:
    image: mongo-express:latest
    ports: 
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db-mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - api-network
    volumes:
      - db-mongo:/data/db
    depends_on:
      - db-mongo


# postgres
# redis
# rabbitmq


 
# networks
networks:
  api-network:
    driver: bridge

# volumes
volumes:
  db-mongo:
  
 